name: Tests

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:3.4.5-slim

    steps:
      - uses: actions/checkout@v5
      - run: |
        apt-get update
        apt-get install -y libtag-dev
      - run: apt list --installed | grep libtag
      - run: bundle install
      - run: bundle exec rake
