name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install taglib
        run: sudo apt-get install libtag1-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
      - name: Run tests
        run: bundle exec rake
