name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:3.4.5-slim

    steps:
      - uses: actions/checkout@v2
      - name: Install taglib
        run: |
          apt-get update
          apt-get install -y --no-install-recommends build-essential pkg-config git ca-certificates curl
          apt-get install -y libtag-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
